home:
    pattern: /
    defaults: { _controller: AppBundle:Home:index }
    requirements: { _method: get }

developer:
    pattern: /developer
    defaults: { _controller: AppBundle:Developer:index }
    requirements: { _method: get }

projects:
    pattern: /projects
    defaults: { _controller: AppBundle:Projects:index }
    requirements: { _method: get }
